Repository octokit/auth-oauth-device.js, pull requests merged in 2023-06, with the labels that each got.

#149 fix(build): switch to esbuild
  package-lock.json
  package.json
  scripts/build.mjs
  src/auth.ts
  src/get-oauth-access-token.ts
  src/hook.ts
  src/index.ts
  src/types.ts
  test/tsconfig.test.json
  tsconfig.json
Labels: Type: Maintenance

#143 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: Type: Maintenance, Type: Breaking change

#154 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
